version: '3.9'


services:
  redis:
    image: redis:7.0.0-alpine3.15

  celery:
    build:
      context: .
    entrypoint: celery -A celery_and_flask_app.celery_ worker -c 2
    depends_on:
      - redis
    volumes:
      - ./app/upscaled_files:/upscaled_files

  app:
    build:
      context: .
    ports:
      - 5000:5000
    entrypoint: gunicorn -b 0.0.0.0:5000 main:app
    depends_on:
      - redis
    volumes:
      - ./app/upscaled_files:/upscaled_files
